### ISSUE TITLE
userSettings and Binaries missing

### ISSUE THREAD

**Issue by entrptaher** [michaelwschultz/timelapse-app#1]
These two separate line points to files/directories that does not exist, nor there is any information available for this.

```
let settingsFileLocation =  userDataPath + '/userSettings.json';
let binaryDest = userDataPath + '/Binaries';
```

**Comment by michaelwschultz** [comment]
@entrptaher hey, sorry I didn't see this sooner. When you run the app for the first time these folders will be created for you!

`const userDataPath = app.getPath('userData')` is defines the path for these two lines.

userDataPath is set to `~/Library/Application Support/Timelapse/` on OSX. It's different on Windows but like I state in the readme. This app is only built for OSX right now.

Does that answer your question? If so, please close this issue. 👍 
If not, let me know!
